include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Type safety and declarations
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    always_require_non_null_named_parameters: true
    type_annotate_public_apis: true
    annotate_overrides: true
    avoid_as: true
    avoid_dynamic_calls: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_returning_null_for_future: true
    avoid_returning_null_for_void: true
    avoid_shadowing_type_parameters: true
    avoid_types_as_parameter_names: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    prefer_typing_uninitialized_variables: true
    prefer_void_to_null: true
    type_init_formals: true

    # Code structure and organization
    avoid_classes_with_only_static_members: true
    avoid_empty_else: true
    avoid_field_initializers_in_const_classes: true
    avoid_relative_lib_imports: true
    avoid_unnecessary_containers: true
    directives_ordering: true
    empty_catches: true
    empty_constructor_bodies: true
    empty_statements: true
    implementation_imports: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true

    # Naming conventions
    camel_case_types: true
    constant_identifier_names: true
    library_names: true
    library_prefixes: true
    non_constant_identifier_names: true
    package_names: true
    package_prefixed_library_names: true

    # Collections and iterables
    avoid_function_literals_in_foreach_calls: true
    iterable_contains_unrelated_type: true
    list_remove_unrelated_type: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    prefer_collection_literals: true
    prefer_contains: true
    prefer_foreach: true
    prefer_iterable_whereType: true
    prefer_spread_collections: true

    # Const and final
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    unnecessary_const: true

    # Control flow
    await_only_futures: true
    avoid_slow_async_io: true
    control_flow_in_finally: true
    curly_braces_in_flow_control_structures: true
    prefer_conditional_assignment: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_if_null_operators: true
    throw_in_finally: true

    # Methods and functions
    avoid_renaming_method_parameters: true
    avoid_return_types_on_setters: true
    prefer_initializing_formals: true
    recursive_getters: true
    unnecessary_overrides: true

    # Operators and expressions
    prefer_equal_for_default_values: true
    prefer_null_aware_operators: true
    unrelated_type_equality_checks: true

    # String operations
    prefer_adjacent_string_concatenation: true
    prefer_interpolation_to_compose_strings: true
    unnecessary_brace_in_string_interps: true
    use_string_buffers: true

    # Code quality and best practices
    cancel_subscriptions: true
    close_sinks: true
    hash_and_equals: true
    overridden_fields: true
    prefer_asserts_in_initializer_lists: true
    prefer_generic_function_type_aliases: true
    prefer_inlined_adds: true
    test_types_in_equals: true
    use_rethrow_when_possible: true
    valid_regexps: true

    # Unnecessary code
    avoid_redundant_argument_values: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_parenthesis: true
    unnecessary_statements: true
    unnecessary_this: true

    # Flutter-specific
    avoid_print: true
    flutter_style_todos: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    use_build_context_synchronously: true
    use_full_hex_values_for_flutter_colors: true
    use_key_in_widget_constructors: true
    use_named_constants: true

    # Function types and syntax
    use_function_type_syntax_for_parameters: true
    use_if_null_to_convert_nulls_to_bools: true
    use_late_for_private_fields_and_variables: true
    use_raw_strings: true
    use_setters_to_change_properties: true
    use_test_throws_matchers: true
    use_to_and_as_if_applicable: true

    # Documentation
    package_api_docs: true
    provide_deprecation_message: true
    slash_for_doc_comments: true

    # Other utilities
    prefer_for_elements_to_map_fromIterable: true
    sort_pub_dependencies: true

analyzer:
  errors:
    subtype_of_sealed_class: ignore
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
